apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    log-bin=mysql-bin
    gtid-mode=ON
    enforce-gtid-consistency=ON
    host_cache_size=0
    skip-name-resolve
    authentication_policy=mysql_native_password
